server:
  port: 8686
  servlet:
    context-path: /@contextPath@
  compression:
    enabled: true
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
spring:
  profiles:
    active: @profileActive@ #环境 dev|prod
  mvc:
    static-path-pattern: /**
  resource:
    #自定义静态资源路径,处理方式见WebMvcConfig.java
    static-locations: classpath:/public/
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    druid:
      aop-patterns: "com.monezhao.mapper.*"
  main:
    banner-mode: off
#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:com/monezhao/**/mapper/xml/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.monezhao.bean.*
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#springboot监控actuator
management:
  endpoints:
    web:
      exposure:
        #include: "*"
        include: info,metrics,httptrace
# 描述信息
info:
  blog-url: http://monezhao.github.io
  author: monezhao
  version: 1.0
async:
  executor:
    thread:
      core-pool-size: 10
      max-pool-size: 20
      queue-capacity: 2000
      name-prefix: async-service-
      keep-alive-seconds: 60
flowable:
  async-executor-activate: false
#  font-name: '思源宋体 CN'
system-config:
  # 新建用户或者重置用户密码默认密码
  defaultPassword: 1
  # 是否使用验证码, 0 使用 1不使用
  useCaptcha: 1
  # jwt过期时间 7d
  expireTime: 604800
  # 登录错误限制
  loginCount: 5
  # 多处登录, 0 可以 1不可以
  multipleLogin: 0
knife4j:
  enable: true
  basic:
    enable: false
    username: admin
    password: 123456
  setting:
    language: zh-CN
    enableVersion: false
    enableFooter: false
    enableFooterCustom: true
#    footerCustomContent: Copyright © MoneZhao(monezhao@163.com). All rights reserved.
    enableSwaggerModels: true
    swaggerModelName: 实体类列表
    enableFilterMultipartApis: true
    enableOpenApi: false